name: Build and Push to Docker Hub with Incremental Tag

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version tag from commit count
        id: vars
        run: echo "VERSION_TAG=v$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fancy-nginx:${{ steps.vars.outputs.VERSION_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fancy-nginx:${{ steps.vars.outputs.VERSION_TAG }}
